# Generated by Django 5.0.4 on 2024-04-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='period',
            field=models.CharField(choices=[('FP', '1-2'), ('SP', '3-4'), ('FR', '5-6'), ('FH', '7-8'), ('FF', '9-10'), ('SX', '11-12')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
