# Generated by Django 5.0.4 on 2024-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_lesson_period_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audience',
            field=models.CharField(max_length=5),
        ),
    ]
