# Generated by Django 5.0.4 on 2024-04-19 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_lesson_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='schedule.subject'),
            preserve_default=False,
        ),
    ]
