# Generated by Django 5.0.4 on 2024-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_department_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='semester',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
