# Generated by Django 5.0.4 on 2024-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_lesson_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='semester',
            field=models.CharField(max_length=50),
        ),
    ]
