# Generated by Django 5.0.4 on 2024-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_lesson_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('MN', 'monday'), ('TU', 'tuesday'), ('WD', 'wednesday'), ('TH', 'thursday'), ('FR', 'friday'), ('ST', 'saturday')], default='monday', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='semester',
            field=models.CharField(max_length=50),
        ),
    ]
