# Generated by Django 5.0.4 on 2024-04-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_lesson_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('MN', 'Понедельник'), ('TU', 'Вторник'), ('WD', 'Среда'), ('TH', 'Четверг'), ('FR', 'Пятница'), ('ST', 'Суббота')], max_length=5),
        ),
    ]
