# Generated by Django 5.0.4 on 2024-04-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_lesson_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
    ]
