# Generated by Django 5.0.4 on 2024-04-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_remove_lesson_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='subjects',
            field=models.ManyToManyField(related_name='department', to='schedule.subject'),
        ),
    ]
